#! /bin/bash
#
# bettercap_switcher - script to switch bettercap on/off
#                  (usually called from the WLANPi menu system)    
#
# Written by Nigel Bowden <wifinigel@gmail.com>.
#
# History:
#
# v0.01 - 31st July 2019 - initial version
#

set -e

NAME=bettercap_switcher
DESC="Script to switch bettercap on/off"
VERSION=0.01

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

###############################################################################
#
# Launch bettercap:
#
###############################################################################
bettercap_start () {
  # If already running, do nothing & return message
  if ! [ -z `pidof bettercap` ]; then
    echo "Bettercap is running."
    return
  fi
  
  # Launch Bettercap as background process (as the wlanpi user)
  # (Output sent to /dev/null so that interactive process returns and
  # doesn't hang calling script)
  # sudo bettercap -caplet https-ui
  su -c 'bettercap -silent -caplet https-ui > /dev/null 2>&1 &'
    
  # Signal that bettercap active
  echo "Bettercap start initiated."

}

###############################################################################
#
# Kill bettercap:
#
###############################################################################
bettercap_stop () {
  # Check Bettercap is running and kill it
  if ! [ -z `pidof bettercap` ]; then
    echo "Killing Bettercap process"
    kill `pidof bettercap`
  else
    echo "Bettercap not running"
    return
  fi
  
  # Bettercap docs also recommend restarting networking when Bettercap
  # stops, so we'll do that for good measure (silently)
  sudo service networking restart
}

###############################################################################
#
# Return bettercap status:
#
###############################################################################
status () {
  # Check if we see the bettercap process and report positive or negative message
  if ! [ -z `pidof bettercap` ]; then
    echo "Bettercap is running"
  else
    echo "Bettercap not running"
    return
  fi
}

###############################################################################
#
# Return script version:
#
###############################################################################
version () {
    N=/etc/wlanpi-bettercap/$NAME
        echo "Version: $N $VERSION" >&2
        exit 1

}

case "$1" in
  start)
        bettercap_start
        ;;
  stop)
        bettercap_stop
        ;;
  status)
        status
        ;;
  version)
        version;;
  *)
        N=/etc/wlanpi-bettercap/$NAME
        echo "Usage: $N {start|stop|status|version}" >&2
        exit 1
        ;;
esac

exit 0

